# Generated by Django 5.2.9 on 2025-12-18 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='showing',
            name='showing_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
