# Generated by Django 5.2.9 on 2025-12-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReviews', '0002_review_created_at_showing_showing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='professional_review_link',
            field=models.URLField(blank=True),
        ),
    ]
