# Generated by Django 5.2.9 on 2025-12-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReviews', '0003_showing_professional_review_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showing',
            name='showing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
